apiVersion: v1
kind: Service
metadata:
  name: myJavaApp-svc
  labels:
    app: myJavaApp
    version: 2.6.1
spec:
  type: NodePort
  ports:
  - port: 8080
    nodePort: 30001
    protocol: TCP
  selector:
    app: myJavaApp
    version: 2.6.1     
